import Head from "next/head";
import Header from "@/components/layout/header";
import MainContent from "@/components/layout/mainContent";
import DiscountBanner from "@/components/discount-banner/DiscountBanner";
import Footer from "@/components/layout/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainContent />
      </main>
    </>
  );
}
